config/routes.rb
Rails.application.routes.draw do

  get 'rates_controller/create'

  root to: "users#home"

  get "/privacy" => "application#privacy"

  get "login" => "users#new", as: :login

  get "/auth/:provider/callback" => "sessions#create", as: :auth_callback
  get "/auth/failure" => "sessions#failure", as: :auth_failure
  delete "/logout" => "sessions#destroy", as: :logout

  resources :microposts#, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :rates

  #nao acabou o tutorial

  resources :users do
    member do
      get :following, :followers
      get :rate
    end
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize(object.errors.count, "coisas erradas.") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Crie um post agora e ganhe pontos!" %>
  </div>
  <%= f.submit "Publicar", class: "btn btn-primary" %>

  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>

<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Arquivo muito grande. Escolha um menor que 5MB.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stats">
      <%= @user.following.count %>
    </strong>
    seguindo
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stats">
      <%= @user.followers.count %>
    </strong>
    seguidores
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to photo_for(current_user), current_user %>
<h1>
  <%= current_user.name %>
</h1> 

<span><%= link_to "Meu perfil", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "post") %></span>