config/routes.rb
Rails.application.routes.draw do

  get 'rates_controller/create'

  root to: "users#home"

  get "/privacy" => "application#privacy"

  get "login" => "users#new", as: :login

  get "/auth/:provider/callback" => "sessions#create", as: :auth_callback
  get "/auth/failure" => "sessions#failure", as: :auth_failure
  delete "/logout" => "sessions#destroy", as: :logout

  resources :microposts#, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :rates

  #nao acabou o tutorial

  resources :users do
    member do
      get :following, :followers
      get :rate
    end
  end

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Social Hero</a>
    </div> <!-- end div class="navbar-header" -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Avalie", rate_user_path(current_user) %>
          <li><%= link_to "Feed", root_path %>
          <li><%= link_to "Pessoas", users_path %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Sair", logout_path, method: "delete" %>
          </li>
        <% end %>
      </ul>
    </div> <!-- end div class="collapse navbar-collapse" -->
  </div> <!-- end div class="container" -->
</div> <!-- end div class="navbar navbar-default navbar-fixed-top" -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social Hero - <%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>